

spring:
  server:
    port: 9000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i8b206.p.ssafy.io:3306/coogether?serverTimezone=Asia/Seoul
    username: i8b206
    password: i8b206
#    url: jdbc:mysql://localhost:3306/coogether?serverTimezone=Asia/Seoul
#    username: ssafy
#    password: ssafy
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging.level:
  org.hibernate.SQL: debug
  com.amazonaws.util.EC2MetadataUtils: error
# org.hibernate.type: trace


